version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "alpine"
  - package-ecosystem: "docker"
    directory: "/docker/hiero/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "maven"
